version: "3.8"
services:
  web:
    build: ./app
    image: 992382460915.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:django_docker_aws_web
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    image: 992382460915.dkr.ecr.us-east-2.amazonaws